# Generated by Django 5.1.1 on 2024-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_userprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='desired_roles',
            field=models.JSONField(),
        ),
    ]
