# Generated by Django 5.1.1 on 2024-10-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_userprofile_desired_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='experience_level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Senior', 'Senior')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full Time'), ('Contract', 'Contract'), ('Part-Time', 'Part Time')], max_length=50),
        ),
    ]
